-- ShopMart - Banner Management (Phase 2 update)
-- Idempotent DDL for the homepage/banner CMS.

CREATE TABLE IF NOT EXISTS banners (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    subtitle    VARCHAR(255),
    image_url   VARCHAR(1024) NOT NULL,
    link_url    VARCHAR(1024),
    position    INTEGER NOT NULL DEFAULT 0,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at   TIMESTAMPTZ,
    ends_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_banners_active ON banners (active, position);
