-- ShopMart - Phase 7 (i18n translations + mobile device tokens)
-- Multi-currency and SEO are config/derived (no tables). Elasticsearch is external.

CREATE TABLE IF NOT EXISTS translations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   BIGINT NOT NULL,
    locale      VARCHAR(16) NOT NULL,
    field       VARCHAR(64) NOT NULL,
    value       VARCHAR(4000) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_translation UNIQUE (entity_type, entity_id, locale, field)
);
CREATE INDEX IF NOT EXISTS idx_translation_lookup ON translations (entity_type, entity_id, locale);

CREATE TABLE IF NOT EXISTS device_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token       VARCHAR(512) NOT NULL,
    platform    VARCHAR(16),
    app_version VARCHAR(32),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_device_token UNIQUE (token)
);
CREATE INDEX IF NOT EXISTS idx_device_user ON device_tokens (user_id);
