-- ShopMart - Super Admin + Attendance additions
-- ddl-auto=update creates these automatically; this file is for reference / manual setup.

-- 1) Attendance (working hours)
CREATE TABLE IF NOT EXISTS attendance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    login_time  TIMESTAMPTZ NOT NULL,
    logout_time TIMESTAMPTZ,
    total_hours DOUBLE PRECISION,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_attendance_user ON attendance (user_id);

-- 2) Promote a user to SUPER_ADMIN (roles live in user_roles)
-- INSERT INTO user_roles (user_id, role)
-- SELECT id, 'ROLE_SUPER_ADMIN' FROM users WHERE email = 'superadmin@shopmart.local'
-- AND NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = users.id AND ur.role='ROLE_SUPER_ADMIN');

-- 3) Create a super admin from scratch (BCrypt of 'Super@12345')
-- INSERT INTO users (name, email, password_hash, email_verified, enabled, provider, created_at, updated_at)
-- VALUES ('Super Admin', 'superadmin@shopmart.local',
--         '$2b$10$vNiLq7CnQRuH5V9FCWzvW.i8r5mTcZ5mBtCDJRnXZLNdaTtKECV2.',  -- replace with hash of Super@12345
--         TRUE, TRUE, 'LOCAL', now(), now());
-- INSERT INTO user_roles (user_id, role)
-- SELECT id, r FROM users CROSS JOIN (VALUES ('ROLE_SUPER_ADMIN'),('ROLE_ADMIN'),('ROLE_CUSTOMER')) AS t(r)
-- WHERE email = 'superadmin@shopmart.local';
