-- ============================================================================
-- ShopMart — Phase 2 schema additions
-- New tables for coupons, reviews, blogs, and in-app notifications.
-- Apply AFTER schema.sql (depends on users / products / orders):
--     psql -d shopmart -f db/phase2.sql
-- Conventions match schema.sql: identity PKs, TIMESTAMPTZ audit columns,
-- NUMERIC(12,2) money.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Coupons + redemptions
-- ----------------------------------------------------------------------------
CREATE TABLE coupons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(255)  NOT NULL,
    description         VARCHAR(255),
    discount_type       VARCHAR(255)  NOT NULL,                 -- PERCENTAGE | FIXED
    discount_value      NUMERIC(12,2) NOT NULL,
    min_order_amount    NUMERIC(12,2),
    max_discount_amount NUMERIC(12,2),
    usage_limit         INTEGER,
    used_count          INTEGER       NOT NULL DEFAULT 0,
    per_user_limit      INTEGER,
    starts_at           TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ,
    active              BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ   DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT uk_coupons_code UNIQUE (code)
);

CREATE TABLE coupon_redemptions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id        BIGINT        NOT NULL,
    user_id          BIGINT        NOT NULL,
    order_id         BIGINT,
    discount_applied NUMERIC(12,2) NOT NULL,
    created_at       TIMESTAMPTZ   DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT fk_redemption_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id) ON DELETE CASCADE,
    CONSTRAINT fk_redemption_user   FOREIGN KEY (user_id)   REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_redemption_order  FOREIGN KEY (order_id)  REFERENCES orders (id)  ON DELETE SET NULL
);
CREATE INDEX idx_redemption_coupon_user ON coupon_redemptions (coupon_id, user_id);

-- ----------------------------------------------------------------------------
-- Reviews (one per user per product; rating drives products.rating_average)
-- ----------------------------------------------------------------------------
CREATE TABLE reviews (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT        NOT NULL,
    user_id           BIGINT        NOT NULL,
    rating            INTEGER       NOT NULL,
    title             VARCHAR(255),
    comment           VARCHAR(2000),
    status            VARCHAR(255)  NOT NULL DEFAULT 'APPROVED',  -- PENDING | APPROVED | REJECTED
    verified_purchase BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ   DEFAULT now(),
    updated_at        TIMESTAMPTZ,
    CONSTRAINT uk_review_product_user UNIQUE (product_id, user_id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user    FOREIGN KEY (user_id)    REFERENCES users (id)    ON DELETE CASCADE
);
CREATE INDEX idx_reviews_product ON reviews (product_id);

-- ----------------------------------------------------------------------------
-- Blog posts (+ tags element collection)
-- ----------------------------------------------------------------------------
CREATE TABLE blog_posts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    slug         VARCHAR(255) NOT NULL,
    excerpt      VARCHAR(500),
    content      TEXT,
    cover_image  VARCHAR(255),
    author_id    BIGINT,
    status       VARCHAR(255) NOT NULL DEFAULT 'DRAFT',   -- DRAFT | PUBLISHED
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT uk_blog_posts_slug UNIQUE (slug),
    CONSTRAINT fk_blog_posts_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_blog_posts_status ON blog_posts (status);

CREATE TABLE blog_post_tags (
    post_id BIGINT       NOT NULL,
    tag     VARCHAR(255),
    CONSTRAINT fk_blog_post_tags_post FOREIGN KEY (post_id) REFERENCES blog_posts (id) ON DELETE CASCADE
);
CREATE INDEX idx_blog_post_tags_post ON blog_post_tags (post_id);

-- ----------------------------------------------------------------------------
-- In-app notifications
-- ----------------------------------------------------------------------------
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    type        VARCHAR(255)  NOT NULL DEFAULT 'SYSTEM',   -- ORDER|PAYMENT|PROMO|REVIEW|SYSTEM
    title       VARCHAR(255)  NOT NULL,
    message     VARCHAR(1000),
    link        VARCHAR(255),
    is_read     BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ   DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user ON notifications (user_id);
