-- ============================================================================
-- ShopMart — Phase 3 schema additions
-- Vendors, multi-warehouse inventory, search logs, and product-view tracking.
-- Apply AFTER schema.sql and phase2.sql (depends on users / products / orders):
--     psql -d shopmart -f db/phase3.sql
-- Conventions match earlier files: identity PKs, TIMESTAMPTZ audit columns,
-- NUMERIC(12,2) money, NUMERIC(5,2) percentages.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Vendors + payouts
-- ----------------------------------------------------------------------------
CREATE TABLE vendors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL,
    store_name      VARCHAR(255)  NOT NULL,
    slug            VARCHAR(255)  NOT NULL,
    description     VARCHAR(2000),
    logo_url        VARCHAR(255),
    status          VARCHAR(255)  NOT NULL DEFAULT 'PENDING',  -- PENDING|APPROVED|SUSPENDED|REJECTED
    commission_rate NUMERIC(5,2)  NOT NULL DEFAULT 10.00,
    contact_email   VARCHAR(255),
    contact_phone   VARCHAR(255),
    created_at      TIMESTAMPTZ   DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT uk_vendors_user UNIQUE (user_id),
    CONSTRAINT uk_vendors_slug UNIQUE (slug),
    CONSTRAINT fk_vendors_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE vendor_payouts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id    BIGINT        NOT NULL,
    amount       NUMERIC(12,2) NOT NULL,
    status       VARCHAR(255)  NOT NULL DEFAULT 'PENDING',     -- PENDING | PAID
    period_start TIMESTAMPTZ,
    period_end   TIMESTAMPTZ,
    paid_at      TIMESTAMPTZ,
    note         VARCHAR(255),
    created_at   TIMESTAMPTZ   DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT fk_payouts_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE
);
CREATE INDEX idx_payouts_vendor ON vendor_payouts (vendor_id);

-- ----------------------------------------------------------------------------
-- Warehouses + per-warehouse inventory + transfers
-- ----------------------------------------------------------------------------
CREATE TABLE warehouses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    code         VARCHAR(255) NOT NULL,
    address_line VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    country      VARCHAR(255),
    postal_code  VARCHAR(255),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT uk_warehouses_code UNIQUE (code)
);

CREATE TABLE warehouse_inventory (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT  NOT NULL,
    product_id   BIGINT  NOT NULL,
    quantity     INTEGER NOT NULL DEFAULT 0,
    reserved     INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT uk_wh_inventory UNIQUE (warehouse_id, product_id),
    CONSTRAINT fk_wh_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE,
    CONSTRAINT fk_wh_inventory_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_wh_inventory_product ON warehouse_inventory (product_id);

CREATE TABLE stock_transfers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_warehouse_id BIGINT  NOT NULL,
    to_warehouse_id   BIGINT  NOT NULL,
    product_id        BIGINT  NOT NULL,
    quantity          INTEGER NOT NULL,
    status            VARCHAR(255) NOT NULL DEFAULT 'COMPLETED', -- PENDING|COMPLETED|CANCELLED
    note              VARCHAR(255),
    created_at        TIMESTAMPTZ DEFAULT now(),
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_transfer_from FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_transfer_to   FOREIGN KEY (to_warehouse_id)   REFERENCES warehouses (id)
);
CREATE INDEX idx_stock_transfers_product ON stock_transfers (product_id);

-- ----------------------------------------------------------------------------
-- Search logs (history + trending)
-- ----------------------------------------------------------------------------
CREATE TABLE search_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    query_text   VARCHAR(255) NOT NULL,
    result_count BIGINT       NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT fk_search_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_search_logs_user ON search_logs (user_id);

-- ----------------------------------------------------------------------------
-- Product views (recently viewed + personalization signal)
-- ----------------------------------------------------------------------------
CREATE TABLE product_views (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT fk_product_views_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_product_views_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_product_views_user ON product_views (user_id, created_at);

-- ----------------------------------------------------------------------------
-- Vendor attribution columns on existing tables
-- products.vendor_id  -> owning vendor (null = first-party / platform product)
-- order_items.vendor_id -> snapshot at order time (no FK, mirrors product_id snapshot)
-- ----------------------------------------------------------------------------
ALTER TABLE products ADD COLUMN vendor_id BIGINT;
ALTER TABLE products ADD CONSTRAINT fk_products_vendor
    FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE SET NULL;
CREATE INDEX idx_products_vendor ON products (vendor_id);

ALTER TABLE order_items ADD COLUMN vendor_id BIGINT;
CREATE INDEX idx_order_items_vendor ON order_items (vendor_id);
