-- ShopMart - Phase 3 (gateways, returns/refunds, loyalty)
-- Idempotent DDL. Payment gateway columns already exist on the payments table
-- (provider, gateway_ref, transaction_id); included here as guards for older schemas.

-- Payments: ensure gateway columns exist
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS gateway_ref VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255);

-- Return / refund requests
CREATE TABLE IF NOT EXISTS return_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    reason           VARCHAR(1000) NOT NULL,
    status           VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    refund_amount    NUMERIC(12, 2),
    admin_note       VARCHAR(1000),
    gateway_refund_id VARCHAR(255),
    processed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_returns_user ON return_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_returns_order ON return_requests (order_id);

-- Loyalty accounts (one per user)
CREATE TABLE IF NOT EXISTS loyalty_accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    balance    INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_loyalty_user UNIQUE (user_id)
);

-- Loyalty ledger
CREATE TABLE IF NOT EXISTS loyalty_transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    points      INTEGER NOT NULL,
    type        VARCHAR(16) NOT NULL,
    order_id    BIGINT,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_loyalty_txn_user ON loyalty_transactions (user_id);
