-- ============================================================================
-- ShopMart — PostgreSQL schema (Phase 1 MVP)
-- Matches the JPA entities in com.shopmart.module.*
--
-- Create the database first (run once, outside this script):
--     CREATE DATABASE shopmart;
-- Then apply this file:
--     psql -d shopmart -f schema.sql
--
-- Money is NUMERIC(12,2); audit timestamps are TIMESTAMPTZ (entities use Instant).
-- Primary keys use identity columns (Hibernate GenerationType.IDENTITY on Postgres).
--
-- If you keep this as the source of truth, set in application.yml:
--     spring.jpa.hibernate.ddl-auto: validate   # or: none
-- so Hibernate checks against this schema instead of mutating it.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Users, roles, addresses
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(255),
    password_hash   VARCHAR(255) NOT NULL,
    avatar_url      VARCHAR(255),
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id  BIGINT       NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_roles UNIQUE (user_id, role)
);

CREATE TABLE addresses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    label       VARCHAR(255),
    full_name   VARCHAR(255),
    phone       VARCHAR(255),
    line1       VARCHAR(255),
    line2       VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    postal_code VARCHAR(255),
    country     VARCHAR(255),
    is_default  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_addresses_user ON addresses (user_id);

-- ----------------------------------------------------------------------------
-- Auth: refresh tokens, OTPs
-- ----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(512) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_token ON refresh_tokens (token);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE otp_verifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    code        VARCHAR(255) NOT NULL,
    purpose     VARCHAR(255) NOT NULL,   -- EMAIL_VERIFICATION | PASSWORD_RESET
    expires_at  TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX idx_otp_email_purpose ON otp_verifications (email, purpose);

-- ----------------------------------------------------------------------------
-- Catalog: categories, brands, products (+ images, variants)
-- ----------------------------------------------------------------------------
CREATE TABLE categories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)  NOT NULL,
    slug             VARCHAR(255)  NOT NULL,
    description      VARCHAR(1000),
    banner_url       VARCHAR(255),
    meta_title       VARCHAR(255),
    meta_description VARCHAR(255),
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

CREATE TABLE brands (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)  NOT NULL,
    slug             VARCHAR(255)  NOT NULL,
    description      VARCHAR(1000),
    logo_url         VARCHAR(255),
    banner_url       VARCHAR(255),
    meta_title       VARCHAR(255),
    meta_description VARCHAR(255),
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT uk_brands_slug UNIQUE (slug)
);

CREATE TABLE products (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL,
    slug             VARCHAR(255)   NOT NULL,
    description      VARCHAR(5000),
    sku              VARCHAR(255),
    price            NUMERIC(12,2)  NOT NULL,
    sale_price       NUMERIC(12,2),
    stock            INTEGER        NOT NULL DEFAULT 0,
    category_id      BIGINT,
    brand_id         BIGINT,
    status           VARCHAR(255)   NOT NULL DEFAULT 'DRAFT',  -- DRAFT|ACTIVE|ARCHIVED|OUT_OF_STOCK
    featured         BOOLEAN        NOT NULL DEFAULT FALSE,
    rating_average   NUMERIC(3,2)   DEFAULT 0,
    rating_count     INTEGER        NOT NULL DEFAULT 0,
    meta_title       VARCHAR(255),
    meta_description VARCHAR(255),
    created_at       TIMESTAMPTZ    DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT uk_products_slug UNIQUE (slug),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_brand    FOREIGN KEY (brand_id)    REFERENCES brands (id)     ON DELETE SET NULL
);
CREATE INDEX idx_product_status   ON products (status);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_brand    ON products (brand_id);
CREATE INDEX idx_products_featured ON products (featured);

CREATE TABLE product_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL,
    url         VARCHAR(255) NOT NULL,
    alt         VARCHAR(255),
    position    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_product_images_product ON product_images (product_id);

CREATE TABLE product_variants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT        NOT NULL,
    sku         VARCHAR(255),
    size        VARCHAR(255),
    color       VARCHAR(255),
    price       NUMERIC(12,2),
    stock       INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_variants_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_product_variants_product ON product_variants (product_id);

-- ----------------------------------------------------------------------------
-- Cart
-- ----------------------------------------------------------------------------
CREATE TABLE carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     BIGINT        NOT NULL,
    product_id  BIGINT        NOT NULL,
    variant_id  BIGINT,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_cart_items_cart ON cart_items (cart_id);

-- ----------------------------------------------------------------------------
-- Wishlist
-- ----------------------------------------------------------------------------
CREATE TABLE wishlist_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    product_id  BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX idx_wishlist_user ON wishlist_items (user_id);

-- ----------------------------------------------------------------------------
-- Orders (+ items). Order items snapshot product name/price, so there is no
-- hard FK from order_items.product_id to products — products may be deleted
-- without erasing order history. Uncomment the constraint if you prefer strict
-- referential integrity over the snapshot model.
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(255)  NOT NULL,
    user_id         BIGINT        NOT NULL,
    status          VARCHAR(255)  NOT NULL DEFAULT 'PENDING',  -- PENDING|CONFIRMED|PACKED|SHIPPED|DELIVERED|CANCELLED|RETURNED
    payment_status  VARCHAR(255)  NOT NULL DEFAULT 'PENDING',  -- PENDING|PAID|FAILED|REFUNDED
    payment_method  VARCHAR(255),
    subtotal        NUMERIC(12,2) NOT NULL DEFAULT 0,
    shipping_fee    NUMERIC(12,2) NOT NULL DEFAULT 0,
    discount        NUMERIC(12,2) NOT NULL DEFAULT 0,
    total           NUMERIC(12,2) NOT NULL DEFAULT 0,
    ship_name        VARCHAR(255),
    ship_phone       VARCHAR(255),
    ship_line1       VARCHAR(255),
    ship_line2       VARCHAR(255),
    ship_city        VARCHAR(255),
    ship_state       VARCHAR(255),
    ship_postal_code VARCHAR(255),
    ship_country     VARCHAR(255),
    created_at      TIMESTAMPTZ   DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT uk_orders_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT        NOT NULL,
    product_id    BIGINT        NOT NULL,
    product_name  VARCHAR(255)  NOT NULL,
    thumbnail     VARCHAR(255),
    quantity      INTEGER       NOT NULL,
    unit_price    NUMERIC(12,2) NOT NULL,
    line_total    NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
    -- , CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- ----------------------------------------------------------------------------
-- Payments
-- ----------------------------------------------------------------------------
CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT        NOT NULL,
    method          VARCHAR(255)  NOT NULL,                  -- COD|UPI|CARD|NETBANKING|WALLET
    amount          NUMERIC(12,2) NOT NULL,
    status          VARCHAR(255)  NOT NULL DEFAULT 'CREATED', -- CREATED|PENDING|SUCCESS|FAILED|REFUNDED
    provider        VARCHAR(255),
    gateway_ref     VARCHAR(255),
    transaction_id  VARCHAR(255),
    failure_reason  VARCHAR(255),
    created_at      TIMESTAMPTZ   DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);
CREATE INDEX idx_payments_order ON payments (order_id);
CREATE INDEX idx_payments_gateway_ref ON payments (gateway_ref);
